### ISSUE TITLE
MASTER PROP TO-DO LIST

### ISSUE THREAD

**Issue by bayreporta** [bayreporta/gimme-props-2016#9]
- [x] Prop 51 Ed bond (MOLLIE DIBS)
- [x] Prop 52 Hospital fees (MOLLIE DIBS) 
- [x] Prop 53 Ballot box budgeting (JOHN DIBS)
- [x] Prop 54 Transparency leg (JOHN DIBS)
- [x] Prop 55 Tax the rich (JOHN DIBS)
- [x] Prop 56 Tobacco tax (MOLLIE DIBS)
- [x] Prop 57 Parole (MOLLIE DIBS)
- [x] Prop 58 Bilingual Ed 
- [x] Prop 59 Citizens United (JOHN-TESTER)
- [x] Prop 60 Condoms (MOLLIE DIBS)
- [x] Prop 61 Drug Price Standards (JOHN)
- [x] Prop 62 Repeal Death penalty/
- [x] Prop 63 Ammunition background check 
- [x] Prop 64 Legalize marijuana (MOLLIE DIBS)
- [x] Prop 65 Plastic bag ban 
- [x] Prop 66 Death Penalty cost savings 
- [x] Prop 67 Plastic Bag Revenue
